sudo: required

language: php
php:
  - 7.3.9

services:
  - docker

addons:
  chrome: stable

branches:
  only:
    - master

before_install:
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs

before_script:
  - cp .env-dist .env
  - export $(cat .env | sed -e /^$/d -e /^#/d | xargs)
  - env
  - docker-compose up -d --build
  - docker ps -a
  - while [ "$(curl -o /dev/null -Isw '%{http_code}\n' http://localhost/api/ping)" -ne "200" ]; do sleep 3; echo "Waiting API to be available..."; done
  - docker logs api
  - cd api
  - composer install
  - cd ..
  - cd backend
  - npm install
  - cd ..
  - cd frontend
  - npm install
  - cd ..

script:
  - cd api
  - composer run sniff
  - MYSQL_PORT=3308 && MYSQL_HOST=127.0.0.1
  - composer run test:unit
  - composer run test:functional
  - cd ..
  - cd frontend
  - npm run lint
  - npm run test
  - npm run e2e
  - cd ..
  - cd backend
  - npm run lint
  - npm run test
  - cd ..

after_script:
  - docker-compose down -t1 -v

notifications:
  email: false
